# Generated by Django 2.2 on 2019-05-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=200)),
                ('Text', models.CharField(max_length=200)),
                ('Filter_ID', models.IntegerField(default=0)),
                ('Device_Type', models.CharField(default='type device missing', max_length=200)),
            ],
        ),
    ]
