# Generated by Django 2.2 on 2019-05-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_filterdevices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.FileField(upload_to='filter')),
                ('added_to_db', models.CharField(choices=[('y', 'added'), ('n', 'not added')], default='n', max_length=1)),
                ('upload_date', models.DateTimeField(verbose_name='upload date')),
            ],
        ),
    ]
