# Generated by Django 2.2 on 2019-05-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_filter_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filters_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters', models.FileField(upload_to='filters')),
                ('added_to_db', models.CharField(choices=[('y', 'added'), ('n', 'not added')], default='n', max_length=1)),
                ('upload_date', models.DateTimeField(verbose_name='upload date')),
            ],
        ),
        migrations.RenameModel(
            old_name='FilterDevices',
            new_name='FiltersDevices',
        ),
        migrations.DeleteModel(
            name='Filter_file',
        ),
    ]
