# Generated by Django 2.2 on 2019-05-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20190511_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filtersdevices',
            old_name='Filter_ID',
            new_name='Tractament1',
        ),
        migrations.AddField(
            model_name='filtersdevices',
            name='Tractament2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filtersdevices',
            name='Tractament3',
            field=models.IntegerField(default=0),
        ),
    ]
