# Generated by Django 2.2 on 2019-05-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20190511_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_file',
            name='filtered_db',
            field=models.CharField(choices=[('y', 'filtered'), ('n', 'not filtered')], default='n', max_length=1),
        ),
    ]
