# Generated by Django 2.2 on 2019-05-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_events_file_filtered_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events_filt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_filt', models.FileField(upload_to='events_filt')),
                ('filtered_db', models.CharField(choices=[('y', 'filtered'), ('n', 'not filtered')], default='n', max_length=1)),
                ('upload_date', models.DateTimeField(verbose_name='upload date')),
            ],
        ),
        migrations.RemoveField(
            model_name='events_file',
            name='filtered_db',
        ),
    ]
