# Generated by Django 2.2 on 2019-05-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20190518_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events_filt',
            old_name='events_filt',
            new_name='events',
        ),
    ]
