# Generated by Django 2.2 on 2019-05-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_auto_20190518_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events_df',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.FileField(upload_to='events_df')),
                ('added_to_df', models.CharField(choices=[('y', 'dataframed'), ('n', 'not dataframed')], default='n', max_length=1)),
                ('upload_date', models.DateTimeField(verbose_name='upload date')),
            ],
        ),
        migrations.CreateModel(
            name='Filters_df',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.FileField(upload_to='filters_df')),
                ('added_to_df', models.CharField(choices=[('y', 'dataframed'), ('n', 'not dataframed')], default='n', max_length=1)),
                ('upload_date', models.DateTimeField(verbose_name='upload date')),
            ],
        ),
    ]
